### ISSUE TITLE
Translate roadmap

### ISSUE THREAD

**Issue by benjamingr** [nodejs/nodejs-he#11]
https://github.com/iojs/roadmap/issues/18

**Comment by benjamingr** [comment]
I PR'd here: @MadaraUchiha @a8m can can anyone review?

**Comment by AvnerCohen** [comment]
I added some comments.

**Comment by benjamingr** [comment]
@AvnerCohen thanks :) I've applied the fixes you suggested - can you have another look?

**Comment by benjamingr** [comment]
Merged, thanks for the help!
