### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by benjamingr** [nodejs/nodejs-he#16]
Personally, knowing the `he` crowd I'm not really convinced a site translation would be meaningful and I'm not sure if people would find it useful.

I know at least some of you monitor the same FB groups I do on FB and social media and people simply don't really care if the site itself is available in Hebrew or not.

That said, I think that perhaps translation of some of the API docs might be useful to people. In novice groups I often see simple "how do I" questions where the OP doesn't have particularly good English and could have used a more approachable reference.

Opinions?

**Comment by AvnerCohen** [comment]
@benjamingr my 2 cents, I think that `en` is so widely used, it is so fundamental to using Node.js, that I think translating this would be of little to no service to anyone out there.
I can think of languages where english is actually a barrier, I don't think it's the case with `he`.
