### ISSUE TITLE
Node.js Internationalization Proposal

### ISSUE THREAD

**Issue by obensource** [nodejs/nodejs-he#17]
Hi there!

On behalf of the [Node.js Community Committee](https://github.com/nodejs/community-committee), I’d like to thank you for your group’s contributions to this awesome project! 👏👏👏

I’m reaching out as a member of our new [Internationalization Working Group](https://github.com/nodejs/i18n), and we’d like to get in touch with you about our proposal around [Internationalization for Node.js](https://medium.com/the-node-js-collection/internationalizing-node-js-fe7761798b0a)!

Our proposed changes would modify the structure of the working model that your group, and all Node.js Localization groups currently observe. The primary difference being that we’d like to introduce a [new translation platform](https://crowdin.com/) to streamline the translation process and setup automated integration of localization into the Node.js project.

If you haven’t seen it already, we’d greatly appreciate if you could please take a moment to review [our new proposal](https://medium.com/the-node-js-collection/internationalizing-node-js-fe7761798b0a) and comment in this issue to let us know if you have any thoughts, questions, or objections to it.

We’d love to hear from you by February 14th, during our consensus seeking period for this proposal. If we’re not able to hear from you in that time, we’ll consider that your opinion of the effort is positive, and press on with it. 

Moving ahead, the i18n Working Group is so thrilled to stay in touch with you and make the translation of Node.js’ content into your language a success!

We’re excited to be in touch again soon, and thank you for working with us!

**Comment by benjamingr** [comment]
The thing is people who use Node.js and speak Hebrew typically get all their technical material in English anyway - just translating the docs won't help that much though I think the people here are up for working out a landing page explaining what node _is_ in Hebrew.

**Comment by AvnerCohen** [comment]
Totally agree. 
In the case of hebrew, it would be a waste of good people's time to translate the full set of documentation.
It would be nice to target specific intro and landing pages, but beyond that, there is no such need.

**Comment by obensource** [comment]
@benjamingr @AvnerCohen thank you for your helpful feedback! I know that the Community Committee and I don't want to propose extra work that won't have return value for l10n groups, and I think that's something I didn't do a great job of expressing in this proposal. Apologies.

We'd love to work with you on anything that you deem helpful to your community, and if that means translating the intro & landing content only for [Nodejs.org](https://nodejs.org/en/)–that's awesome! 

Here's the thing–Crowdin projects will present all text in the Node.js project as available to translate, but there's nothing stopping any l10n group from only translating what they need. The rest will gracefully fall back to English in production. I think this should make it easy to do based on your needs and priority.

Thanks again, and I hope that we can help your community achieve anything you need regarding i18n as we work on this. Cheers! 🍻

**Comment by benjamingr** [comment]
Sure, and thanks for the initiative. The HE team hasn't been active at all for the last year and a half but a bunch of us here are contributors regardless of translation and are willing to help with the "important parts" translation. https://iojs.org/he/index.html is getting outdated 😅  

The new proposal looks nice - can you please ping us again when it is possible to start logging in and translate?

**Comment by obensource** [comment]
@benjamingr absolutely! Thanks a bunch for keeping me up to date, I'll be in touch soon! 🙌

**Comment by benjamingr** [comment]
Ok, I'm going to go ahead and close this. If you feel like there is more discussion to be had - feel free to reopen :)

**Comment by obensource** [comment]
@benjamingr sounds good to me. Thanks again!
